"""init deleted john

Revision ID: e5b7d412a1b8
Revises: 
Create Date: 2026-06-10 16:33:48.072477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b7d412a1b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nigers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nigers',
    sa.Column('moped', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('loh', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('moped', name=op.f('nigers_pkey'))
    )
    # ### end Alembic commands ###
